#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="2.51.1"
BASEURL="https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/"
SRCDIR="fastfetch-$VERSION"
TARBALL="$VERSION.tar.gz"

download() {
  cd "$DIR"
  echo "downloading fastfetch source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting fastfetch source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL"
  cd "$SRCDIR"
  mkdir -p build
  cd build
  cmake -DENABLE_ELF=OFF -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath-link=$ROOTFS/usr/lib" ..
}

makeinstall() {
  echo "building fastfetch..."
  if ! test -d "$DIR/$SRCDIR/build"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR/build"

  cmake --build . -j "${JOBS:-8}" --target fastfetch
  install -Dm755 fastfetch "$ROOTFS/usr/bin"
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for fastfetch

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
