#!/bin/sh

# The tag list is not ordered newest-first -- ancient pre-rename tags (v1.0.0,
# v1.0.1 from 2022) sort to the top -- so filter to bare X.Y.Z releases and
# pick the numerically largest.
curl https://api.github.com/repos/fastfetch-cli/fastfetch/tags 2> /dev/null \
  | jq -r '.[].name' \
  | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
  | awk -F. '{printf "%03d.%03d.%03d %s\n", $1, $2, $3, $0 }' \
  | sort -n \
  | tail -n 1 \
  | awk '{print $2}'
