#!/bin/sh

mountpoint -q /proc || mount -o nosuid,noexec,nodev -t proc proc /proc
mountpoint -q /sys || mount -o nosuid,noexec,nodev -t sysfs sys /sys
mountpoint -q /run || mount -o mode=0755,nosuid,nodev -t tmpfs run /run
mountpoint -q /dev || mount -o mode=0755,nosuid -t devtmpfs dev /dev

DRIVE=$(sed -nE 's/.*\broot=([^[:space:]]*).*/\1/p' /proc/cmdline)

if grep 'debug' /proc/cmdline; then
  echo "requested debug shell, going into ash"
  exec /bin/sh </dev/console >/dev/console 2>&1
fi

/usr/sbin/udevd --daemon
/usr/sbin/udevadm trigger --type=subsystems --action=add
/usr/sbin/udevadm trigger --type=devices --action=add
/usr/sbin/udevadm settle

case "$DRIVE" in
  /dev*)
    mount "$DRIVE" /mnt
  ;;
  UUID=*)
    UUID=$(echo "$DRIVE" | cut -d'=' -f 2 | tr -d '"')
    DEVICE=""
    for i in $(seq 1 30); do
      DEVICE=$(blkid | sed -nE "s|([^:]*).*UUID=\"$UUID\".*|\1|p")
      if test -n "$DEVICE" ; then break; fi
      echo "Waiting for device with UUID=$UUID..."
      sleep 1
    done
    if test -z "$DEVICE"; then
      echo "It's cooked there's no device with uuid $UUID"
      exit 1
    fi
    mount "$DEVICE" /mnt
  ;;
  *)
    echo "xoops it's joever chat didn't get the right root param (dev or uuid)"
    echo "we got $DRIVE"
    exit 1
  ;;
esac

exec switch_root /mnt /sbin/init
