#!/bin/sh

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR" || exit 1

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

OPENSSL=3.5.0
BASEURL="https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL"
SRCDIR="openssl-$OPENSSL"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR" || exit 1
  echo "downloading openssl source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR" || exit 1
  echo "extracting openssl source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL" || exit 1
  cd "$SRCDIR" || exit 1
  
  ./Configure linux-"$(echo "$TARGET" | cut -d'-' -f 1)" \
    no-tests \
    --prefix=/usr --openssldir=/etc/ssl\
    -DDEFAULT_CERT_FILE=\"/etc/ssl/cert.pem\" \
    -DDEFAULT_CERT_DIR=\"/etc/ssl/certs\"
}

makeinstall() {
  echo "building openssl..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR" || exit 1

  make -j${JOBS:-8} || exit 1
  make -j${JOBS:-8} DESTDIR=$ROOTFS install || exit 1
}

clear() {
  cd "$DIR" || exit 1
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR" || exit 1
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for openssl

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
