#!/bin/sh

set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

# tzdata requires explicit updates.

VERSION="2025b"
BASEURL="https://data.iana.org/time-zones/releases"
SRCDIR="tzdata$VERSION"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR"
  echo "downloading tzdata source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
  else
    curl -LOf $BASEURL/$TARBALL
  fi

}

extract() {
  cd "$DIR"
  echo "extracting tzdata source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  mkdir -p "$SRCDIR" && cd "$SRCDIR"
  tar xzf "$DIR/$TARBALL"
}

makeinstall() {
  echo "building tzdata..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"
  mkdir -p "$ROOTFS/usr/share/zoneinfo"
  zic -d "$ROOTFS/usr/share/zoneinfo" africa antarctica asia \
    australasia backward backzone etcetera europe northamerica southamerica
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for tzdata

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
