#!/bin/sh

curl -fLs https://ftp.gnu.org/gnu/gmp/ \
  | grep -oE 'gmp-[0-9,\.]*\.tar\.gz' \
  | sed 's/gmp-\([0-9,\.]*\)\.tar\.gz/\1/g' \
  | awk -F. '{printf "%03d%03d%03d %s\n", $1, $2, $3, $0}' \
  | uniq \
  | sort -n \
  | tail -n 1 \
  | cut -d ' ' -f 2
