Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "fb"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "screen"
    Device "fb"
EndSection

Section "ServerLayout"
    Identifier "layout"
    Screen "screen"
EndSection
