#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="1.2.5"
BASEURL=https://musl.libc.org/releases
SRCDIR="musl-$VERSION"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR"
  echo "downloading libc source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting libc source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL"
  cd "$SRCDIR"
  patch -p1 < "$DIR/utmp.patch"
  ./configure --prefix="/usr" --syslibdir="/lib" --with-sysroot="${ROOTFS:-/}"
}

makeinstall() {
  echo "building libc..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"

  make -j${JOBS:-8}
  make DESTDIR=$ROOTFS install
}

clear() {
  cd "$DIR"
  rm -rf *.tgz *.tar.xz *.tar.bz2 *.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for libc

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the tarball into ../gcc
clear|clean|c -> clean everything except the tarballs (prevent extra downloads)
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
