#!/bin/sh

curl -fLs https://www.x.org/releases/individual/xcb/ \
  | grep -oE 'xcb-util-renderutil-[0-9.]+\.tar\.xz' \
  | sed -E 's/^xcb-util-renderutil-([0-9.]+)\.tar\.xz$/\1/' \
  | sort -V \
  | tail -n1
