#!/bin/sh

curl https://api.github.com/repos/libffi/libffi/tags 2> /dev/null \
  | jq -r '.[].name' \
  | grep -E '^v[0-9,\.]+$' \
  | grep -vE 'dev|rc' \
  | sed "s/^v\([0-9,\.]*\)$/\1/" \
  | head -n 1
