#!/bin/sh

curl https://api.github.com/repos/mirror/busybox/tags 2> /dev/null \
  | jq -r '.[].name' \
  | grep -E '^[0-9,\_]+$' \
  | grep -vE 'dev|rc' \
  | sed "s/^v\([0-9,\.]*\)$/\1/" \
  | head -n 1 \
  | tr '_' '.'
