#!/bin/sh

curl --retry 10 --retry-delay 5 --retry-connrefused "https://ftp.gnu.org/gnu/readline/" 2> /dev/null \
  | grep -E '\"readline-[0-9,\.]*\.tar\.gz\"' \
  | sed \
    -e 's/^.*href="readline-\([0-9\.]*\)\.tar\.gz\".*$/\1/gp'\
  | awk -F. '{printf "%02d.%03d.%03d %s\n", $1, $2, $3, $0 }' \
  | sort -n \
  | uniq \
  | awk '{print $2}' \
  | tail -n 1
