#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="2.45"
BASEURL="https://sourceware.org/pub/binutils/releases"
SRCDIR="binutils-$VERSION"
TARBALL="$SRCDIR.tar.xz"
BUILDDIR="dist"

download() {
  cd "$DIR"
  echo "downloading binutils source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting binutils source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xf "$TARBALL"

  mkdir -p "$DIR/$BUILDDIR"
  cd "$DIR/$BUILDDIR"
  "$DIR/$SRCDIR/configure" \
    --prefix="/usr" \
    --exec-prefix="/usr" \
    --target="$TARGET" \
    --disable-fixed-point \
    --disable-libquadmath \
    --disable-decimal-float \
    --enable-default-pie \
    --enable-default-ssp \
    --program-prefix= \
    --disable-separate-code \
    --disable-nls \
    --with-sysroot=/ \
    --with-build-sysroot="${ROOTFS:-/}"\
    --disable-bootstrap \
    --disable-werror \
    --disable-multilib \
    --disable-lto \
    --enable-tls \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-libctf \
    CC="$CC $CFLAGS -fPIC"\
    CXX="$CXX $CXXFLAGS -fPIC"\
   
}

makeinstall() {
  echo "building binutils..."
  if ! test -d "$DIR/$BUILDDIR" -a -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi

  cd "$DIR/$BUILDDIR"
  make -j${JOBS:-8}
  make -j${JOBS:-8} DESTDIR=$ROOTFS install
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL" "$BUILDDIR"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for binutils

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
