#!/bin/sh

curl https://sourceware.org/pub/binutils/releases/ 2> /dev/null \
  | grep '.tar.xz"' \
  | grep -v 'gold' \
  | sed \
    -e 's/^.*href="binutils-\([0-9\.]*\)\.tar.xz\".*$/\1/gp'\
  | sort -n \
  | tail -n 1
