#!/bin/sh

curl https://www.freedesktop.org/software/libevdev/ 2> /dev/null \
  | grep -oE 'libevdev-[0-9][0-9.]*\.tar\.xz' \
  | sed -e 's/^libevdev-\(.*\)\.tar\.xz$/\1/' \
  | sort -V \
  | tail -n 1
