#!/bin/sh

curl https://www.kernel.org/releases.json 2>/dev/null \
  | jq -rc '.releases[] | select(.moniker=="stable") | .source' \
  | sed 's/^.*linux-\([0-9\.]*\)\.tar.xz.*$/\1/g' \
  | awk -F. '{printf "%02d.%03d.%03d %d.%d.%d\n", $1, $2, $3, $1, $2, $3 }' \
  | sort -n \
  | uniq \
  | awk '{print $2}' \
  | tail -n 1
