#!/bin/sh

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR" || exit 1

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the juniosenv!" && \
  exit 1;
}

#BASEURL="https://ftp.gnu.org/gnu/ncurses"
BASEURL="https://dev.mit.junic.kim/pkgs"
SRCDIR="ncurses-6.5"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR" || exit 1
  echo "downloading ncurses source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR" || exit 1
  echo "extracting ncurses source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL" || exit 1
  cd "$SRCDIR" || exit 1
  ./configure --without-cxx --without-cxx-binding\
    --without-shared --prefix=/usr\
    --exec-prefix=/usr --enable-static\
    --host=$TARGET\
    --with-sysroot="${ROOTFS:-/}"\
    --without-ada \
    --without-tests \
    --enable-termcap\
    CFLAGS="$CFLAGS -fPIC"
}

makeinstall() {
  echo "building ncurses..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR" || exit 1

  make -j${JOBS:-8} || exit 1
  make DESTDIR=$ROOTFS install || exit 1
}

clear() {
  cd "$DIR" || exit 1
  rm -rf *.tgz *.tar.xz *.tar.bz2 *.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR" || exit 1
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for ncurses

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
