#!/bin/sh

curl https://www.freedesktop.org/software/fontconfig/release/ 2> /dev/null \
  | grep -oE 'fontconfig-[0-9][0-9.]*\.tar\.xz' \
  | sed -e 's/^fontconfig-\(.*\)\.tar\.xz$/\1/' \
  | sort -V \
  | tail -n 1
