#!/bin/sh

set -eu

curl https://api.github.com/repos/pkgconf/pkgconf/tags 2> /dev/null \
  | jq -r '.[].name' \
  | grep -E '^pkgconf-[0-9\.]+$' \
  | sed 's/^pkgconf-\([0-9\.]*\)$/\1/g' \
  | head -n 1
