#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="1.0.8"
BASEURL="https://sourceware.org/pub/bzip2"
SRCDIR="bzip2-$VERSION"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR"
  echo "downloading bzip2 source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting bzip2 source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL"
  cd "$SRCDIR"
  ./configure --prefix="/usr" --exec-prefix="/usr" --target="$TARGET"\
    --with-sysroot="${ROOTFS:-/}"
  sed -i \
    -e "s|^PREFIX=.*|PREFIX=$ROOTFS/usr|" \
    -e '/^CC=.*/d' \
    -e '/^AR=.*/d' \
    -e '/^RANLIB=.*/d' \
    -e '/^CFLAGS=.*/d' \
    -e '/^LDFLAGS=.*/d' \
    -e '/ln -s/d' \
    Makefile
}

makeinstall() {
  echo "building bzip2..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"

  make -j${JOBS:-8}
  ln -sfn bzgrep "$ROOTFS/usr/bin/bzegrep"
  ln -sfn bzgrep "$ROOTFS/usr/bin/bzfgrep"
  ln -sfn bzmore "$ROOTFS/usr/bin/bzless"
  ln -sfn bzdiff "$ROOTFS/usr/bin/bzcmp"
  make -j${JOBS:-8} install
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for bzip2

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
