#!/bin/sh

set -eu

# sob perl still refuses to build :/ will be WIP

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="5.40.2"
BASEURL=https://www.cpan.org/src/5.0
SRCDIR="perl-$VERSION"
TARBALL="$SRCDIR.tar.xz"

download() {
  cd "$DIR"
  echo "downloading perl source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
  else
    curl -LOf $BASEURL/$TARBALL
  fi
}

extract() {
  cd "$DIR"
  echo "extracting perl source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xf "$TARBALL"
  #tar --strip-components=1 -zxf perl-cross-1.6.2.tar.gz -C "$SRCDIR"
  chmod -R u+w "$SRCDIR"
  cd "$SRCDIR"
  sed -i \
    -e "s/Makefile=Makefile/Makefile=build.Makefile/g" \
    -e '1a\# vim:ft=sh' \
    -e "s/\$(MAKE) depend MAKEDEPEND=/\$(MAKE) -f build.Makefile depend/g"\
    Makefile.SH
  ./Configure -des -Dprefix=/usr \
    -Dcflags="$CFLAGS $LDFLAGS" \
    -Dusedevel \
    -Dvendorprefix=/usr
  echo 'd_eaccess=undef' >> ./config.sh
  echo '#undef HAS_EACCESS' >> ./config.h
  #echo 'firstmakefile=build.Makefile' >> ./config.sh
  cp "$DIR/write_buildcustomize.pl" .
}

makeinstall() {
  echo "building perl..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"

  make -f build.Makefile -j${JOBS:-8}
  make -f build.Makefile -j${JOBS:-8} DESTDIR=$ROOTFS install
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for perl

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
