#!/bin/sh

# LMAO yeah this script is basically a bunch of stubs, but it's better than
# creating a separate edge case :)

set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

download() {
  true
}

extract() {
  true
}

makeinstall() {
  echo "installing tests..."
  install -d "$ROOTFS/usr/test"
  install -m755 ./scripts/*-test "$ROOTFS/usr/test"
  install -Dm755 ./mimux-test "$ROOTFS/usr/bin/"
}

clear() {
  true
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for tests

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
