#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="1.65.0"
BASEURL="https://github.com/nghttp2/nghttp2/releases/download/v$VERSION"
SRCDIR="nghttp2-$VERSION"
TARBALL="$SRCDIR.tar.xz"

download() {
  cd "$DIR"
  echo "downloading nghttp2 source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting nghttp2 source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xf "$TARBALL"
  cd "$SRCDIR"
  ./configure --prefix="/usr" --exec-prefix="/usr" --target="$TARGET"\
    --with-sysroot="${ROOTFS:-/}"
}

makeinstall() {
  echo "building nghttp2..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"

  make -j${JOBS:-8}
  make -j${JOBS:-8} DESTDIR=$ROOTFS install
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for nghttp2

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
