#!/bin/sh

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR" || exit 1

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

SRCDIR="runit-2.2.0"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR" || exit 1
  echo "downloading runit source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf https://smarden.org/runit/$TARBALL
}

extract() {
  cd "$DIR" || exit 1
  echo "extracting runit source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL" --strip-components=1 || exit 1
  cd "$DIR/$SRCDIR" || exit 1

  sed -i 's/gcc/$CC/g' src/find-systype.sh
  sed -i 's/gcc/$CC $CFLAGS/g' src/conf-cc
  sed -i 's/gcc/$CC $LDFLAGS/g' src/conf-ld
}

makeinstall() {
  echo "building runit..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR" || exit 1

  # FORCE static linking everything
  LDFLAGS="$LDFLAGS" package/compile || exit 1
  install -Dm755 command/runit-init   $ROOTFS/sbin/init
  install -Dm755 command/*            $ROOTFS/sbin/
}

clear() {
  cd "$DIR" || exit 1
  rm -rf *.tgz *.tar.xz *.tar.bz2 *.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR" || exit 1
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for runit on macos

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the tarball into ../gcc
clear|clean|c -> clean everything except the tarballs (prevent extra downloads)
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
