#!/bin/sh

if [ -f /run/chrony/chronyd.pid ]; then
  pid=$(cat /run/chrony/chronyd.pid)
  if ! kill -0 "$pid" 2>/dev/null; then
    rm -f /run/chrony/chronyd.pid
  fi
fi
exec chronyd -f /etc/chrony.conf
