#!/bin/sh
set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

# Don't upgrade to 3.14.0 this is an error from the version script.
VERSION="3.13.6"
BASEURL="https://www.python.org/ftp/python/$VERSION"
SRCDIR="Python-$VERSION"
TARBALL="$SRCDIR.tar.xz"

# python actually just shits itself without this.
export LD_LIBRARY_PATH="$ROOTFS/lib:$ROOTFS/usr/lib"

download() {
  cd "$DIR"
  echo "downloading python3 source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
    return
  fi

  curl -LOf $BASEURL/$TARBALL
}

extract() {
  cd "$DIR"
  echo "extracting python3 source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xf "$TARBALL"
  cd "$SRCDIR"
  cp -a "$DIR/Setup" ./Modules/Setup.local
  ./configure --prefix="/usr" --exec-prefix="/usr"\
    --with-sysroot="${ROOTFS:-/}"\
    --with-openssl="/usr"\
    --enable-shared \
    --disable-static \
    --without-static-libpython \
    --disable-test-modules \
    CFLAGS="$CFLAGS -fPIC"\
    LDFLAGS="$LDFLAGS"
}


makeinstall() {
  echo "building python3..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"
  make -j"${JOBS:-8}"
  make -j"${JOBS:-8}" DESTDIR="$ROOTFS" install

  MAJORMINOR="$(echo "$VERSION" | cut -d '.' -f 1-2)"
  ln -sfn "python$MAJORMINOR" "$ROOTFS/usr/bin/python3"
  ln -sfn "pip3" "$ROOTFS/usr/bin/pip"
  # reduce bloat.
  rm -rf "$ROOTFS/usr/lib/python$MAJORMINOR/test"
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for python3

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
