#!/bin/sh

curl "https://api.github.com/repos/pnggroup/libpng/tags?per_page=100" 2> /dev/null \
  | jq -r '.[].name' \
  | grep -E '^v1\.6\.[0-9]+$' \
  | sed -e 's/^v\(.*\)$/\1/' \
  | sort -V \
  | tail -n 1
