name: Linting-ish Tasks

on:
  push:
    branches: [ main ]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    env:
      MIMUX_API_KEY: ${{ secrets.MIMUX_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl gzip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Run versions checker
        run: |
          python ./tools/versions.py

      - name: Upload version results
        run: |
          cd monitor || exit 1
          go run . send -P ../dist/mimux_updates.json -U https://mxm.mit.junic.kim

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          shellcheck ./tools/*.sh ./core/*/version ./core/*/build ./misc/* ./init/*/build ./cross/build ./buildall.sh
