name: Linting-ish Tasks

on:
  push:
    branches: [ main ]

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl gzip

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run versions checker
        run: |
          python ./tools/versions.py
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run versions checker
        run: |
          shellcheck ./tools/*.sh ./core/*/build ./misc/*\
          ./init/*/build ./cross/build ./buildall.sh
          python ./tools/versions.py
