#!/bin/sh

set -eu

DIR="$(realpath "$(dirname "$0" )" )"
cd "$DIR"

# You MUST make sure that we are in a correct environment.
test -z "$INOSENV" && {
  echo "You cannot run this script while not in the mimuxenv!" && \
  exit 1;
}

VERSION="1.14.6"
BASEURL="https://mandoc.bsd.lv/snapshots"
SRCDIR="mandoc-$VERSION"
TARBALL="$SRCDIR.tar.gz"

download() {
  cd "$DIR"
  echo "downloading mandoc source..."
  if test -f "$TARBALL"; then
    echo "$TARBALL exists, skipping..."
  else
    curl -LOf $BASEURL/$TARBALL
    if ! sha256sum -c $SRCDIR.sha256; then
      echo "sha256 failed oops"
      rm -rf "$TARBALL"
      exit 1
    fi
  fi
}

extract() {
  cd "$DIR"
  echo "extracting mandoc source..."
  if ! test -f "$TARBALL"; then
    echo "No tarball to operate on!"
    exit 1
  fi

  tar xzf "$TARBALL"
  cd "$SRCDIR"
  sed -i \
    -e "/^CC=.*$/d"\
    -e "/^AR=.*$/d"\
    -e "/^CFLAGS=.*$/d"\
    -e "/^LDFLAGS=.*$/d"\
    -e "/^PREFIX=.*$/d"\
    -e "/^WWWPREFIX=.*$/d"\
    configure
  PREFIX="/usr"\
  WWPREFIX="/var/www"\
    ./configure --prefix="/usr" --exec-prefix="/usr" --target="$TARGET"\
    --with-sysroot="${ROOTFS:-/}"
}

makeinstall() {
  echo "building mandoc..."
  if ! test -d "$DIR/$SRCDIR"; then
    echo "No source directory to operate on!"
    exit 1
  fi
  cd "$DIR/$SRCDIR"

  make -j"${JOBS:-8}"
  make -j"${JOBS:-8}" DESTDIR="$ROOTFS" install
}

clear() {
  cd "$DIR"
  rm -rf ./*.tgz ./*.tar.xz ./*.tar.bz2 ./*.tar.gz "$SRCDIR" "$TARBALL"
}

cd "$DIR"
case "$1" in
  download|d)
    download
    ;;
  extract|e)
    extract
    ;;
  makeinstall|mi)
    makeinstall
    ;;
  clear|clean|c)
    clear
    ;;
  all|a)
    download && extract && makeinstall
    ;;
  *)
    cat <<EOF
Build script for mandoc

download|d -> download the tarball
extract|e -> extract and patch the tarball
makeinstall|mi -> make and install the build artifacts
clear|clean|c -> clean all artifacts
all|a -> clean, and then go through everything.
EOF
    exit 1
    ;;
esac
