#!/bin/sh

curl -s https://mandoc.bsd.lv/snapshots/ --retry 5 \
  | grep -oE 'mandoc-[0-9,\.]*\.tar\.gz' \
  | sed 's/mandoc-\([0-9,\.]*\)\.tar\.gz/\1/g' \
  | awk -F. '{printf "%03d%03d%03d %s\n", $1, $2, $3, $0}' \
  | uniq \
  | sort -n \
  | tail -n 1 \
  | cut -d ' ' -f 2
