#!/bin/sh

curl https://mirrors.edge.kernel.org/pub/linux/utils/kbd/ 2> /dev/null \
  | grep '.tar.xz"' \
  | grep -v 'gold' \
  | sed \
    -e "s/^.*\<a//g" \
    -e "s/<\/a.*$//g" \
    -e 's/^.*href="kbd-\([0-9\.]*\)\.tar.xz\".*$/\1/gp'\
  | sort -n \
  | tail -n 1
